# Generated by Django 3.2 on 2023-07-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.BooleanField(choices=[(True, '男'), (False, '女')], default=True, verbose_name='性别'),
        ),
    ]
