# Generated by Django 3.2 on 2023-07-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类型名称', max_length=20, verbose_name='类型名称')),
            ],
        ),
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=100, verbose_name='标题')),
                ('content', models.TextField(help_text='新闻内容', verbose_name='新闻内容')),
                ('read', models.IntegerField(help_text='阅读量', verbose_name='阅读量')),
                ('commnet', models.IntegerField(help_text='评论数量', verbose_name='评论数量')),
                ('type', models.ManyToManyField(help_text='新闻类型', to='news.NewsType', verbose_name='新闻类型')),
            ],
        ),
    ]
