# Generated by Django 3.2 on 2023-07-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsinfo',
            options={'verbose_name': '新闻信息'},
        ),
        migrations.AlterModelOptions(
            name='newstype',
            options={'verbose_name': '新闻类型'},
        ),
        migrations.AlterModelTable(
            name='newsinfo',
            table='news',
        ),
        migrations.AlterModelTable(
            name='newstype',
            table='type',
        ),
    ]
