# Generated by Django 3.2 on 2023-07-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20230714_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsinfo',
            old_name='commnet',
            new_name='comment',
        ),
    ]
